services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: github_db
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq 
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: ./backend
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: github_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      QUEUE_NAME: import_queue
    ports:
      - "3000:3000"
    volumes:
      - shared-tmp:/tmp

  worker:
    build: ./backend
    environment:
      WORKER: "true" 
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: github_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    volumes:
      - shared-tmp:/tmp

volumes:
  shared-tmp:
  db-data:
  rabbitmq-data: