services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: github_db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: ./backend
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: github_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      QUEUE_NAME: import_queue
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./backend:/app
      - /app/node_modules

  worker:
    build: ./backend
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: github_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      QUEUE_NAME: import_queue
      WORKER: "true"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  db-data: