services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-github_db}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-password}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: ./backend
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: ${DB_USER:-root}
      DATABASE_PASSWORD: ${DB_PASSWORD:-root}
      DATABASE_NAME: ${DB_NAME:-github_db}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-user}:${RABBITMQ_PASSWORD:-password}@rabbitmq:5672
    ports:
      - "3000:3000"
    volumes:
      - shared-tmp:/tmp
    depends_on:
      - db
      - rabbitmq

  worker:
    build: ./backend
    environment:
      WORKER: "true"
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: ${DB_USER:-root}
      DATABASE_PASSWORD: ${DB_PASSWORD:-root}
      DATABASE_NAME: ${DB_NAME:-github_db}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-user}:${RABBITMQ_PASSWORD:-password}@rabbitmq:5672
    volumes:
      - shared-tmp:/tmp
    depends_on:
      - db
      - rabbitmq

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  shared-tmp:
  db-data:
  rabbitmq-data: