services:
  mariadb:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: github_repos
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 5s
      timeout: 5s
      retries: 30

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 30

  backend:
    build: ./backend
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: github_repos
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

volumes:
  mariadb-data: